#!/bin/bash
set -e

# These are passed from docker-compose, which gets them from .env generated by deploy.sh
PUID=${PUID:-1000}
PGID=${PGID:-1000}
LIBVIRT_GID=${LIBVIRT_GID:-104}

echo "Starting backend container with PUID: $PUID, PGID: $PGID, LIBVIRT_GID: $LIBVIRT_GID"

# Create brokenops group if it doesn't exist
if ! getent group brokenops >/dev/null; then
    groupadd -o -g "$PGID" brokenops
fi

# Create libvirt group if it doesn't exist to match host
if ! getent group libvirt >/dev/null; then
    groupadd -o -g "$LIBVIRT_GID" libvirt
fi

# Create brokenops user if it doesn't exist
if ! getent passwd brokenops >/dev/null; then
    useradd -o -u "$PUID" -g "$PGID" -m brokenops
fi

# Ensure user is in libvirt group
usermod -aG libvirt brokenops

# Change ownership of /app directory itself so SQLite can write
chown brokenops:brokenops /app

# Change ownership of DB if it exists
if [ -f /app/brokenops.db ]; then
    chown brokenops:brokenops /app/brokenops.db*
fi

# Ensure we have permissions to the parent data dir, though the user should own it
# We won't chown /var/run/libvirt because we don't own it

# Drop privileges and execute the CMD as the brokenops user
exec gosu brokenops "$@"
